version: "3"

services:
  backend-dev:
    image: sanbonai06/bankids-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "8080"

  vote-dev:
    image: sanbonai06/vote-server:master
    container_name: vote-dev
    hostname: vote-dev
    expose:
      - "5050"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"